package io.github.haohaozaici.greendaoupdate.model.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import io.github.haohaozaici.greendaoupdate.model.db.Sample;

import io.github.haohaozaici.greendaoupdate.model.db.dao.SampleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sampleDaoConfig;

    private final SampleDao sampleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sampleDaoConfig = daoConfigMap.get(SampleDao.class).clone();
        sampleDaoConfig.initIdentityScope(type);

        sampleDao = new SampleDao(sampleDaoConfig, this);

        registerDao(Sample.class, sampleDao);
    }
    
    public void clear() {
        sampleDaoConfig.clearIdentityScope();
    }

    public SampleDao getSampleDao() {
        return sampleDao;
    }

}
