package io.github.haohaozaici.greendaoupdate.model.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import io.github.haohaozaici.greendaoupdate.model.db.Sample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SAMPLE".
*/
public class SampleDao extends AbstractDao<Sample, Long> {

    public static final String TABLENAME = "SAMPLE";

    /**
     * Properties of entity Sample.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property User_id = new Property(2, String.class, "user_id", false, "USER_ID");
        public final static Property Batch_no = new Property(3, String.class, "batch_no", false, "BATCH_NO");
        public final static Property Details = new Property(4, String.class, "details", false, "DETAILS");
        public final static Property Test1 = new Property(5, String.class, "test1", false, "TEST1");
    }


    public SampleDao(DaoConfig config) {
        super(config);
    }
    
    public SampleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SAMPLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DATE\" TEXT NOT NULL ," + // 1: date
                "\"USER_ID\" TEXT NOT NULL ," + // 2: user_id
                "\"BATCH_NO\" TEXT NOT NULL ," + // 3: batch_no
                "\"DETAILS\" TEXT NOT NULL ," + // 4: details
                "\"TEST1\" TEXT);"); // 5: test1
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SAMPLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Sample entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDate());
        stmt.bindString(3, entity.getUser_id());
        stmt.bindString(4, entity.getBatch_no());
        stmt.bindString(5, entity.getDetails());
 
        String test1 = entity.getTest1();
        if (test1 != null) {
            stmt.bindString(6, test1);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Sample entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDate());
        stmt.bindString(3, entity.getUser_id());
        stmt.bindString(4, entity.getBatch_no());
        stmt.bindString(5, entity.getDetails());
 
        String test1 = entity.getTest1();
        if (test1 != null) {
            stmt.bindString(6, test1);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Sample readEntity(Cursor cursor, int offset) {
        Sample entity = new Sample( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // date
            cursor.getString(offset + 2), // user_id
            cursor.getString(offset + 3), // batch_no
            cursor.getString(offset + 4), // details
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // test1
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Sample entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.getString(offset + 1));
        entity.setUser_id(cursor.getString(offset + 2));
        entity.setBatch_no(cursor.getString(offset + 3));
        entity.setDetails(cursor.getString(offset + 4));
        entity.setTest1(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Sample entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Sample entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Sample entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
